version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=my_password
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    volumes:
      - mongodb_data:/data/db
      - ./yelp_dataset:/tmp/yelp_dataset
volumes:
  mongodb_data:
