version: '3.8'
services:
  arangodb:
    image: "redis:7.2.3"
    ports:
      - "6379:6379"
    environment:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    volumes:
      - redis_data:/var/lib/redis
      - ./yelp_dataset:/tmp/yelp_dataset
volumes:
  redis_data:
